"""Add AppConfig model for configuration storage

Revision ID: 713d0bff7430
Revises: aea595ef3091
Create Date: 2025-07-18 11:14:51.242227

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '713d0bff7430'
down_revision = 'aea595ef3091'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_chat_history_thread_id'), 'chat_history', ['thread_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_history_thread_id'), table_name='chat_history')
    # ### end Alembic commands ###
